usr/lib/libankidrive.a
usr/include/ankidrive/advertisement.h
usr/include/ankidrive/common.h
usr/include/ankidrive/protocol.h
usr/include/ankidrive/uuid.h
usr/include/ankidrive/vehicle_gatt_profile.h
usr/include/ankidrive/version.h
usr/lib/libbzle.a
usr/include/bzle/gatt/gatt.h
usr/include/bzle/gatt/att.h
usr/include/bzle/gatt/utils.h
usr/include/bzle/gatt/gattrib.h
usr/include/bzle/bluetooth/btio.h
usr/include/bzle/bluetooth/hci_lib.h
usr/include/bzle/bluetooth/uuid.h
usr/include/bzle/bluetooth/bluetooth.h
usr/include/bzle/bluetooth/sdp.h
usr/include/bzle/bluetooth/sco.h
usr/include/bzle/bluetooth/hci.h
usr/include/bzle/bluetooth/sdp_lib.h
usr/include/bzle/bluetooth/l2cap.h


